### ISSUE TITLE
Falha de segurança.

### ISSUE THREAD

**Issue by ernanicavila** [devsakae/myFood#2]
https://github.com/devsakae/myFood/blob/b574d3ca3c5bf081d03cbc75c2989469728db4be/src/components/Comidas/Disponiveis.jsx#L6

Ao você deixar o link disponível, ele quebra a segurança do projeto. O recomendado é você por em um .env e enviar a variável de ambiente através do deploy.

**Comment by devsakae** [comment]
Fixed. Thanks @ernanicavila 

https://github.com/devsakae/myFood/commit/76793075a0b9e4f86016c2352904187830c09b00
